config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
  end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #      :recoverable, :rememberable, :validatable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  # validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    users = User.all

    if users
      render json: { status: 'Success', message: 'Users fetched successfully', data: users }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch users', errors: users.errors }, status: :bad_request
    end
  end

  def show
    user = User.find_by(id: params[:id])

    if user
      render json: { status: 'Success', message: 'User fetched successfully', data: user }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch user', errors: user.errors }, status: :bad_request
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @all_users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out_and_redirect
    else
      @user = User.includes(posts: [:user, { comments: :user }]).find(params[:id])
      @most_recent_posts = @user.most_recent_posts
      @user_posts = @user.posts
      redirect_to users_path, alert: 'User not found' unless @user
    end
  end

  def sign_out_and_redirect
    sign_out current_user
    redirect_to new_user_session_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<% @all_users.each do |user| %>
<%= link_to user_path(user) do %>
  <div class="user">
    <div class="photo"><% if user.photo.present? %>
      <%= image_tag user.photo, size: "100x100" %>
    <% else %>
      <%= image_tag "https://unsplash.com/photos/F_-0BxGuVvo", size: "100x100" %>
    <% end %>
    </div>
    <div class="user-details">
    <h3><%= user.name %></h3>
    <p class="user-posts">Number of Posts: <%= user.posts.count %></p>
    </div>
  </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="user">
  <div class="photo">
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, size: "100x100" %>
    <% else %>
      <%= image_tag "https://unsplash.com/photos/F_-0BxGuVvo", size: "100x100" %> <% end %>
  </div>
  <div class="user-details">
    <h3><%= @user.name %></h3>
    <p class="user-posts">Number of Posts: <%= @user.posts.count %></p>
  </div>
</div>
<div class="bio-posts">
  <p class="p-bio"><%= @user.bio %></p>
  <% if @most_recent_posts.any? %> <% @most_recent_posts.each do |post| %>
  <div class="recent-posts">
    <p><%= post.text %></p>
    <p class="counters">
      comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
    </p>
  </div>
  <% end %> <% else %>
  <p>No recent posts.</p>
  <% end %>
</div>


<br>

<button id="create-post-btn">
  <%= link_to 'Create Post', new_user_post_path(@user) %>
</button>

<br> <br> <br>

<button id="show-more-btn">
  <%= link_to 'Show More', user_posts_path(@user) %>
</button>