config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
  end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :user, foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts

  def display_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts
    author.increment!(:posts_counter)
  end

  def decrement_user_post_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.includes(:posts).find(params[:user_id])

    if @posts
      render json: { status: 'Success', message: 'Posts fetched successfully', data: @posts }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch posts!', errors: @posts.errors }, status: :bad_request
    end
  end

  def show
    @post = Post.includes(:author).find_by(author_id: params[:user_id], id: params[:id])
    @user = @post.author

    if @post
      render json: { status: 'Success', message: 'Post fetched successfully', data: @post }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch post!', errors: @post.errors }, status: :bad_request
    end
  end
end

app/controllers/posts_controller.rb
require 'will_paginate/array'

class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: %i[index show new create]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:user, comments: :user).order(created_at: :desc).paginate(page: params[:page],
                                                                                            per_page: 5)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    render 'show'
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  def new
    set_user
    @post = @user.posts.build
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      puts @post.errors.full_messages
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def authorize_user
    @post = Post.find(params[:id])
    return if @post.user == current_user

    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to root_path
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="user">
  <!-- Your user details display here -->
  <div class="photo">
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, size: "100x100" %>
    <% else %>
    <%= image_tag "https://unsplash.com/photos/F_-0BxGuVvo", size: "100x100" %>
    <% end %>
  </div>
  <div class="user-details">
    <h3><%= @user.name %></h3>
    <p class="user-posts">Number of Posts: <%= @user.posts.count %></p>
  </div>
</div>

<div class="bio-posts">
  <!-- Display all user posts here -->
  <% @posts.each do |post| %>
    <div class="recent-posts">
      <%= link_to user_post_path(@user, post) do %>
        <p><%= post.text %></p>
        <p class="counters">comments: <%= post.comments_counter %>, <span>Likes: <%= post.likes_counter %></span></p>
        <% if post.display_comments.any? %>
        
          <h3 class="comments-heading">Comments:</h3>
          <ul class="comments-list">
            <% post.display_comments.each do |comment| %>
              <li>
                <%= comment.user.name %>: <%= comment.text %>
                <% if comment.user == current_user %> <!-- Check if the comment belongs to the current user -->
                  <%= button_to 'Delete', user_post_comment_path(@user, post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>

      <div class="button-container">
        <div class="like">
          <%= button_to 'Like Post', user_post_likes_path(@user, post), method: :post %>
        </div>
  
        <div class="create-comment-btn">
          <%= link_to 'Create Comment', new_user_post_comment_path(@user, post) %>
        </div>
      </div>

      <div class="delete-post">
        <!-- Display the delete post button here -->
        <% if can? :destroy, post %>
          <button class="delete-post-btn">
            <%= link_to 'Delete post', user_post_path(@user, post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </button>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="new_post">
  <h2>Create New Post</h2>
  <div>
    <%= link_to 'Create New Post', new_user_post_path(@user) %>
  </div>
</div>

<br> <br>
<div class="pagination-links">
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<div class="new-post-form">
  <h3>Create a New Post</h3>
  <%= form_with(model: @post, url: user_posts_path(@user), local: true, method:
  :post) do |form| %>

  <div class="field">
    <%= form.label :title %> <%= form.text_field :title %>
  </div>
  <div class="field"><%= form.label :text %> <%= form.text_area :text %></div>
  <%= form.button "Create Post", class: "button" %> <% end %>
</div>

app/views/posts/show.html.erb
<div class="recent-posts">
  <p><%= @post.text %></p>
  <p class="counters">
    Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes.count %>
  </p>

  <% if @post.display_comments.any? %>
    <h3 class="comments-heading">Comments:</h3>
    <ul class="comments-list">
      <% @post.display_comments.each do |comment| %>
        <li>
          <span class="comment-author"><%= comment.author.name %>:</span> <%= comment.text %>
          <% if comment.author == current_user %>
            <button class="delete-comment-btn">
              <%= link_to 'Delete', user_post_comment_path(@user, comment.post, comment.id), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
            </button>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="button">
    <% if can? :destroy, @post %>
      <button class="delete-post-btn">
        <%= link_to 'Delete post', user_post_path(@user, @post), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </button>
    <% end %>
  </div>

  <div class="button-container">
    <div class="like">
      <%= button_to 'Like Post', user_post_likes_path(@user, @post), method: :post, class: "like" %>
    </div>

    <div class="create-comment-btn">
      <%= link_to 'Create Comment', new_user_post_comment_path(@user, @post) %>
    </div>
  </div>
  
</div>

<div class="roll-back">
  <%= link_to 'Back', user_posts_path(@user) %>
</div>